#!/bin/ash

. /etc/rc.d/functions

case "$1" in
start)
	echo -n "Starting ntpd: "
	/bin/ntpd -p timesrv1.esrf.fr
	check_status
	;;
stop)
	echo -n "Stopping ntpd: "
	killall ntpd
	check_status
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
