[ $LFS_THIS_BOARD_NAME != 'comex' ] && return

LFS_THIS_SOFT_IS_ENABLED=1
LFS_THIS_SOFT_DEPS='pcidrvgen'
LFS_THIS_SOFT_URL=file://$LFS_THIS_SOFT_DIR/libtst.tar.gz
LFS_THIS_SOFT_BUILD_METHOD=make

LFS_THIS_SOFT_MAKE_ARGS=\
" CROSS_COMPILE=$LFS_CROSS_COMPILE"\
" PREFIX=$LFS_HOST_INSTALL_DIR/lib"\
" CFLAGS=-I$LFS_SRC_DIR/pcidrvgen"
