#!/bin/ash

. /etc/rc.d/functions

case "$1" in
start)
	is_alive=no
	ping segsrv > /dev/null 2>&1 && is_alive=yes
	if [ $is_alive == 'yes' ]; then
	    echo -n "Mounting segfs: "
	    < /proc/mounts grep segfs || mount -t nfs -overs=3,rw,rsize=8192,wsize=8192,nolock segsrv:/segfs /segfs
	    check_status
	fi
	;;
stop)
	echo -n "Unmounting segfs: "
	< /proc/mounts grep segfs && umount /segfs
	check_status
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
