#!/bin/ash

. /etc/rc.d/functions

case "$1" in
start)
	echo -n "Mounting segfs: "
	< /proc/mounts grep segfs || mount /segfs
	check_status
	;;
stop)
	echo -n "Unmounting segfs: "
	< /proc/mounts grep segfs || umount /segfs
	check_status
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
