export LFS_TARGET_ARCH=armv6
export LFS_CROSS_COMPILE=$LFS_CROSS_COMPILE_armv6
export LFS_CTNG_VERS=1.18.0
export LFS_DROPBEAR_VERS=2012.55
export LFS_LINUX_VERS=3.6.1
export LFS_LINUX_ARCH=arm
export LFS_BUSYBOX_VERS=1.21.0
export LFS_ZLIB_VERS=1.2.7
