#!/bin/ash

. /etc/rc.d/functions

case "$1" in
start)
	echo -n "Starting epcidrv: "
	/sbin/insmod /lib/modules/`uname -r`/dance/epcidrv.ko
	check_status
	;;
stop)
	echo -n "Stopping epcidrv: "
	/sbin/rmmod epcidrv
	check_status
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
