#!/bin/ash

. /etc/rc.d/functions
. /etc/dance/profile

case "$1" in
start)
	export PATH=$DANCE_BIN_DIR:$PATH
	export LD_LIBRARY_PATH=$DANCE_LIB_DIR:$LD_LIBRARY_PATH

	for n in $DANCE_APP_NAMES; do
	    echo -n "Starting DANCE application $n: "
	    [ -x $DANCE_BIN_DIR/$n ] && $DANCE_BIN_DIR/$n > /dev/null 2>&1 &
	    check_status
	done
	;;
stop)

	for n in $DANCE_APP_NAMES; do
	    echo -n "Stopping DANCE application $n: "
	    /sbin/kill -9 `pidof $n` 2> /dev/null
	    check_status
	done
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
