#!/bin/ash

. /etc/rc.d/functions
. /etc/dance/profile

case "$1" in
start)
	echo -n 'starting ebone driver: '
	/sbin/insmod $DANCE_MOD_DIR/ebone.ko
	major=`dmesg | grep '\[ ebone \] major: ' | tail -n1 | cut -d: -f2`
	for minor in `seq 0 7`; do
	    mknod /dev/ebone$minor c $major $minor;
	done
	check_status

	export PATH=$DANCE_BIN_DIR:$PATH
	export LD_LIBRARY_PATH=$DANCE_LIB_DIR:$LD_LIBRARY_PATH

	for n in $DANCE_APP_NAMES; do
	    echo -n "Starting DANCE application $n: "
	    [ -x $DANCE_BIN_DIR/$n ] && $DANCE_BIN_DIR/$n
	    check_status
	done

	;;
stop)

	for n in $DANCE_APP_NAMES; do
	    echo -n "Stopping DANCE application $n: "
	    /sbin/kill -9 `pidof $n` 2> /dev/null
	    check_status
	done

	echo -n 'stopping ebone driver: '
	for minor in `seq 0 7`; do
	    rm /dev/ebone$minor
	done
	/sbin/rmmod ebone
	check_status

	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
